# Generated by Django 3.0.3 on 2020-03-18 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0002_pontosturisticos_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturisticos',
            name='enderecos',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='enderecos.Enderecos'),
        ),
    ]
