............................................................
Mathias Fernandes Duarte Coelho
NUSP: 10734352
Email: mathfern444@gmail.com
EmailUSP: mathfernandes@usp.br
............................................................
Mude o style da tag <body> para outro tipo de fonte. 
Substitua os <span> (nickname, favorites, hometown) com as informações de algum personagem.
Crie um novo elemento img e coloque uma imagem do personagem escolhido. E acrescente o elemento na página.
