spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-auth
    username: postgres
    password: Postgres2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#spring.application.name=user
